import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#181818',
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 32,
    paddingHorizontal: 20,
    paddingBottom: 8,
    backgroundColor: '#181818',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  notificationButton: {
    marginLeft: 12,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 20,
    padding: 6,
  },
  searchButton: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 20,
    padding: 6,
  },
  greetingContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 0,
  },
  greetingEmoji: {
    fontSize: 18,
    marginBottom: 2,
  },
  greetingText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 2,
  },
  greetingSubText: {
    color: '#b3b3b3',
    fontSize: 15,
    fontWeight: '400',
  },
  // Section styles
  section: {
    marginTop: 18,
    marginBottom: 8,
    paddingLeft: 20,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
    marginRight: 20,
  },
  sectionTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    letterSpacing: 0.2,
  },
  horizontalList: {
    gap: 12,
    paddingRight: 20,
  },
  // Track card styles
  trackCard: {
    width: 110,
    marginRight: 12,
    backgroundColor: '#232323',
    borderRadius: 16,
    padding: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  trackArtwork: {
    width: 80,
    height: 80,
    borderRadius: 12,
    marginBottom: 8,
    backgroundColor: '#333',
  },
  trackTitle: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 2,
    width: '100%',
    textAlign: 'center',
  },
  trackArtist: {
    color: '#b3b3b3',
    fontSize: 13,
    width: '100%',
    textAlign: 'center',
  },
  genreCard: {
    flex: 1,
    margin: 8,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    height: 90,
    minWidth: 140,
    maxWidth: '48%',
    overflow: 'hidden',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 4,
  },
  genreIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    marginBottom: 8,
    backgroundColor: '#222',
  },
  genreName: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  genreRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 0,
  },
  genreList: {
    paddingRight: 20,
    paddingLeft: 0,
    paddingBottom: 8,
  },
}); 